[package]
name = "ckb-chain"
version = "0.114.0-pre"
license = "MIT"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2021"
description = "CKB Blockchain Service, Importing Blocks"
homepage = "https://github.com/nervosnetwork/ckb"
repository = "https://github.com/nervosnetwork/ckb"

[dependencies]
ckb-logger = { path = "../util/logger", version = "= 0.114.0-pre" }
ckb-metrics = { path = "../util/metrics", version = "= 0.114.0-pre" }
ckb-types = { path = "../util/types", version = "= 0.114.0-pre" }
ckb-shared = { path = "../shared", version = "= 0.114.0-pre" }
ckb-chain-spec = { path = "../spec", version = "= 0.114.0-pre" }
ckb-store = { path = "../store", version = "= 0.114.0-pre" }
ckb-verification = { path = "../verification", version = "= 0.114.0-pre" }
ckb-verification-contextual = { path = "../verification/contextual", version = "= 0.114.0-pre" }
ckb-verification-traits = { path = "../verification/traits", version = "= 0.114.0-pre" }
ckb-systemtime = { path = "../util/systemtime", version = "= 0.114.0-pre" }
ckb-stop-handler = { path = "../util/stop-handler", version = "= 0.114.0-pre" }
ckb-proposal-table = { path = "../util/proposal-table", version = "= 0.114.0-pre" }
ckb-error = { path = "../error", version = "= 0.114.0-pre" }
ckb-app-config = { path = "../util/app-config", version = "= 0.114.0-pre" }
ckb-rust-unstable-port = { path = "../util/rust-unstable-port", version = "= 0.114.0-pre" }
ckb-channel = { path = "../util/channel", version = "= 0.114.0-pre" }
faux = { version = "^0.1", optional = true }
ckb-merkle-mountain-range = "0.5.2"
ckb-constant = { path = "../util/constant", version = "= 0.114.0-pre" }
ckb-util = { path = "../util", version = "= 0.114.0-pre" }
crossbeam = "0.8.2"
ckb-network = { path = "../network", version = "= 0.114.0-pre" }
tokio = { version = "1", features = ["sync"] }
ckb-tx-pool = { path = "../tx-pool", version = "= 0.114.0-pre"}
minstant = "0.1.4"
ckb-db = { path = "../db", version = "= 0.114.0-pre" }
ckb-db-schema = { path = "../db-schema", version = "= 0.114.0-pre" }
dashmap = "4.0"

[dev-dependencies]
ckb-test-chain-utils = { path = "../util/test-chain-utils", version = "= 0.114.0-pre" }
ckb-dao-utils = { path = "../util/dao/utils", version = "= 0.114.0-pre" }
ckb-reward-calculator = { path = "../util/reward-calculator", version = "= 0.114.0-pre" }
ckb-tx-pool = { path = "../tx-pool", version = "= 0.114.0-pre", features = ["internal"] }
ckb-jsonrpc-types = { path = "../util/jsonrpc-types", version = "= 0.114.0-pre" }
ckb-network = { path = "../network", version = "= 0.114.0-pre" }
lazy_static = "1.4"
tempfile.workspace = true
ckb-systemtime = { path = "../util/systemtime", version = "= 0.114.0-pre" ,features = ["enable_faketime"]}

[features]
default = []
mock = ["faux"]
portable = ["ckb-store/portable"]
march-native = ["ckb-store/march-native"]
